apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: My workflow
on:
  push:
    branches:
      - "**"
jobs:
  build:
    steps:
      - name: Say hello
        uses: docker://golang:1.20.3-alpine3.17
        shell: sh
        run: |
          echo "hello world"
    needs:
      - Scan
  Scan:
    steps:
      - name: Scan
        uses: cloudbees-io/sonarqube-bundled-sast-scan-code@v2
        run: ""
        kind: scan
        with:
          language: JAVA
        shell: ""
    environment: ""
